version: "2"
services:
  softenq-api:
    build: .
    environment:
      - PG_DB=softenq
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  redis:
    image: redis:alpine
    restart: always

  db:
    image: postgres
    restart: always
